### PR TITLE
Feature/ocr model

### PR DESCRIPTION
**Pull request by Quang-Duy**
# Description

I integrated Google Vision OCR API into the application. We can connect to Google OCR API at anytime. I also created a method to get the prediction from the data point. Upon that, I improved the model so that it always return the necessary info if the model can recognize the characters. Unit testing as well as instruction to use the function are included and ready to merge into main branch.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Raise errors if Google Credential Keys not found, causing failure connecting to Google Vision API
- [X] Raise errors if files not found and gives current directory
- [X] Check return type as well as expected outputs after invoking the methods (with a different data point)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by soma-y1029 — CHANGES_REQUESTED** [review]
Should not reveal API keys in github. 
you can use config.py and add it to gitignore.
Also, since you already pushed this ocr model brunch, please re-generate new keys.
(And why htmlcov files are pushed...? it in the ignore...)
Other works look great!!

**Review by Quang-Duy — COMMENTED** [review]
I removed htmlcov as well as credential keys

**Review by soma-y1029 — APPROVED** [review]
Good To Go!

**Review by jeromestrada — APPROVED** [review]
LGTM!

**Pull request merged**
